# Generated by Django 4.1.2 on 2023-06-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='dep_img',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
