# Generated by Django 4.1.2 on 2023-06-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='dep_spec',
            new_name='doc_spec',
        ),
    ]
