# Generated by Django 4.1.2 on 2023-06-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_rename_dep_spec_doctors_doc_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_img',
            field=models.ImageField(upload_to='images1'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_phone', models.CharField(max_length=10)),
                ('p_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctors')),
            ],
        ),
    ]
